config/routes.rb
Quill::Application.routes.draw do

  resources :contents

  match '/categories' => 'categories#index'

  match '/archives' => 'archives#index'
  match '/archives/category/:category' => 'archives#category'
  match '/archives/date/:year' => 'archives#date'
  match '/archives/date/:year/:month' => 'archives#date'

  resources :pages do
    collection do
      post 'sort'
    end
  end

  match '/feed' => 'posts#feed', :as => :feed, :defaults => { :format => 'atom' }

  resources :posts do
    resources :comments
  end

  devise_for :authors do
    get 'login' => 'devise/sessions#new'
    post 'login' => 'devise/sessions#create'
    get 'logout' => 'devise/sessions#destroy'
  end

  root :to => 'homepage#index'

end

app/models/content.rb
class Content < ActiveRecord::Base
  validates :file,      :presence => true
  
  mount_uploader :file, ContentUploader
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  respond_to :html, :js

  def create
    if author_signed_in?
      @content = Content.new(params[:content])

      @content.save

      respond_with @content
    end
  end

  def destroy
    if author_signed_in?
      @content = Content.find(params[:id])

      @content.destroy

      respond_with @content
    end
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_content.html.slim
div class="file" id=dom_id(content)
  span= content.file.url
  = link_to 'Delete', content_url(content), :confirm => "Are you sure?", :method => :delete, :remote => true, :class => "delete"

app/views/contents/_form.html.slim
= form_for(@new_content, :remote => true) do |f|
  #content_errors
    = f.error_messages

  p
    = f.label :file
    = f.file_field :file

  p
    = f.submit

app/views/contents/_index.html.slim
div id="new_content" class="reveal-modal"
  h1 New File
  = render :partial => 'contents/form'

  h1 Current Files
  div class="files"
    div id="file-spinner"
    = render @contents