config/routes.rb
Quill::Application.routes.draw do

  resources :contents

  match '/categories' => 'categories#index'

  match '/archives' => 'archives#index'
  match '/archives/category/:category' => 'archives#category'
  match '/archives/date/:year' => 'archives#date'
  match '/archives/date/:year/:month' => 'archives#date'

  resources :pages do
    collection do
      post 'sort'
    end
  end

  match '/feed' => 'posts#feed', :as => :feed, :defaults => { :format => 'atom' }

  resources :posts do
    resources :comments
  end

  devise_for :authors do
    get 'login' => 'devise/sessions#new'
    post 'login' => 'devise/sessions#create'
    get 'logout' => 'devise/sessions#destroy'
  end

  root :to => 'homepage#index'

end

app/views/pages/_edit.html.slim
div id='editPage' class='reveal-modal'
  h1 Edit Page

  = form_for(@page, :remote => true) do |f|
    #edit-page-errors
      = f.error_messages

    p
      = f.label :title
      = f.text_field :title

    p
      = f.label :icon
      = f.file_field :icon

    p
      = f.label :header
      = f.check_box :header
    p
      = f.label :sidebar
      = f.check_box :sidebar

    p
      = f.label :content
      = f.text_area :content

    p
      = f.submit

  a class='close-reveal-modal' &#215;

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :header %><br />
    <%= f.check_box :header %>
  </div>
  <div class="field">
    <%= f.label :sidebar %><br />
    <%= f.check_box :sidebar %>
  </div>
  <div class="field">
    <%= f.label :rank %><br />
    <%= f.number_field :rank %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/_new.html.slim
div id='newPage' class='reveal-modal'
  h1 New Page

  = form_for(@new_page, :remote => true) do |f|
    #new-page-errors
      = f.error_messages

    p
      = f.label :title
      = f.text_field :title
    p
      = f.label :icon
      = f.file_field :icon
    p
      = f.label :header
      = f.check_box :header
    p
      = f.label :sidebar
      = f.check_box :sidebar
    p
      = f.label :content
      = f.text_area :content
    p
      = f.hidden_field :rank, :value => Page.count + 2
      = f.submit

  a class='close-reveal-modal' &#215;

app/views/pages/_page.html.slim
figure class="project" id="aside_page_#{page.id}"
  = link_to page_url(page) do
    img src=page.icon.url
    figcaption= page.title

app/views/pages/_sort.html.slim
div id="sortPages" class="reveal-modal"
  h1 Reorder Pages

  ul id="page_sort" data-update-url="#{sort_pages_url}"
    - @sort_pages.each do |page|
      = content_tag_for :li, page do
        img class="handle" src=image_path("drag.png") 
        span= page.title

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Slug</th>
    <th>Header</th>
    <th>Sidebar</th>
    <th>Rank</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.title %></td>
    <td><%= page.content %></td>
    <td><%= page.slug %></td>
    <td><%= page.header %></td>
    <td><%= page.sidebar %></td>
    <td><%= page.rank %></td>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/show.html.slim
title #{site_title} | #{@page.title}

article
  header
    h2= link_to @page.title, page_url(@page)
    p= markdown @page.content

= render 'layouts/admin_bar'