config/routes.rb
Quill::Application.routes.draw do

  resources :contents

  match '/categories' => 'categories#index'

  match '/archives' => 'archives#index'
  match '/archives/category/:category' => 'archives#category'
  match '/archives/date/:year' => 'archives#date'
  match '/archives/date/:year/:month' => 'archives#date'

  resources :pages do
    collection do
      post 'sort'
    end
  end

  match '/feed' => 'posts#feed', :as => :feed, :defaults => { :format => 'atom' }

  resources :posts do
    resources :comments
  end

  devise_for :authors do
    get 'login' => 'devise/sessions#new'
    post 'login' => 'devise/sessions#create'
    get 'logout' => 'devise/sessions#destroy'
  end

  root :to => 'homepage#index'

end

app/models/post.rb
class Post < ActiveRecord::Base

  validates :title,     :presence => true,
                        :length => { :minimum => 3, :maximum => 75 }
  
  validates :content,   :presence => true                      
                        
  belongs_to :author
  has_many :post_categories
  has_many :categories, :through => :post_categories
  has_many :comments, :order => "created_at ASC"

  attr_reader :category_tokens
  
  extend FriendlyId
  friendly_id :title, :use => :slugged
  

  def article
    self.content.gsub('<!-- excerpt -->', '')
  end

  def excerpt
    self.content.split('<!-- excerpt -->')[0]
  end

  def category_tokens=(tokens)
    ids = Array.new
    tokens.split(",").each do |c| 
      if Category.exists?(:name => c)
        cat = Category.find_by_name(c)
      else
        cat = Category.new(:name => c)
        cat.save
      end

      ids.push(cat.id)
    end

    self.category_ids = ids
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :html, :js

  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    if author_signed_in?
      @post = Post.new(params[:post])
      @post.author = current_author
      
      @post.save

      respond_with @post
    end
  end

  def update
    if author_signed_in?
      @post = Post.find(params[:id])

      @post.update_attributes(params[:post])

      respond_with @post
    end
  end

  def destroy
    if author_signed_in?
      @post = Post.find(params[:id])
      @post.destroy

      respond_with @post
    end
  end
  
  def feed
    @title = "Quill Feed"
    @posts = Post.order("created_at DESC")
    @updated = @posts.first.updated_at unless @posts.empty?
    
    respond_to do |format|
      format.atom { render :layout => false }
      format.rss { redirect_to feed_path(:format => :atom), :status => :moved_permanently }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_edit.html.slim
div id='editPost' class='reveal-modal'
  h1 Edit Post

  = form_for(@post, :remote => true) do |f|
    #edit-post-errors
      = f.error_messages

    p
      = f.label :title
      = f.text_field :title, :value => @post.title

    p
      = f.label :content
      = f.text_area :content, :value => @post.content

    p
      = f.label :category_tokens, "Categories"
      = f.text_field :category_tokens, "data-pre" => @post.categories.map(&:name).join(","), :class => "tokenize"

    p Content Uploads coming soon!
    br

    p
      = f.submit

  a class='close-reveal-modal' &#215;

app/views/posts/_excerpt.html.slim
article
  header
    h2= link_to post.title, post_url(post)
    span
      | Date:
      time= post.created_at.strftime(' %B %d, %Y')
  .preview
    p= markdown post.excerpt
    footer
      .meta
        span
          | Categories: 
          = raw post.post_categories.map { |c| link_to c.category.name, archives_path + '/category/' + c.category.slug }.to_sentence
      span.readmore
        = link_to(post_url(post)) do
          input type='submit' value='Read More'

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_field :slug %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_new.html.slim
div id='newPost' class='reveal-modal'
  h1 New Post

  = form_for(@new_post, :remote => true) do |f|
    #new-post-errors
      = f.error_messages

    p
      = f.label :title
      = f.text_field :title

    p
      = f.label :content
      = f.text_area :content

    p
      = f.label :category_tokens, "Categories"
      = f.text_field :category_tokens, :class => "tokenize"

    p Content Uploads coming soon!
    br

    p
      = f.submit

  a class='close-reveal-modal' &#215;

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Author</th>
    <th>Slug</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= post.author %></td>
    <td><%= post.slug %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/show.html.haml
-provide :header, "| " + @post.title

%article
  %header
    %h2= link_to @post.title, post_url(@post)

  %p= markdown @post.content

  %footer
    .meta
      %span
        Posted on
        = @post.created_at.strftime('%B %d, %Y') + '. '
        - if @post.created_at != @post.updated_at
          Updated on
          = @post.updated_at.strftime('%B %d, %Y') + '. '
        Categories:
        = raw @post.post_categories.map { |c| link_to c.category.name, archives_path + '/category/' + c.category.slug }.to_sentence

  #comments
    %h3= pluralize @post.comments.count, 'Comment'
    = render :partial => 'comments/comment', :collection => @post.comments

    = render :partial => 'comments/form'

app/views/posts/show.html.slim
title #{site_title} | #{@post.title}

article
  header
    h2= link_to @post.title, post_url(@post)

  p= markdown @post.article

  footer
    .meta
      span
        | Posted by #{@post.author.name} on 
        = @post.created_at.strftime('%B %d, %Y') + '. '
        - if @post.created_at != @post.updated_at
          | Updated on 
          = @post.updated_at.strftime('%B %d, %Y') + '. '
        | Categories: 
        = raw @post.post_categories.map { |c| link_to c.category.name, archives_path + '/category/' + c.category.slug }.to_sentence

      - if @post.author.google_id?
        / Google Author Support. Display is set to none by default
        = link_to @post.author.name, "https://plus.google.com/#{@post.author.google_id}?rel=author", :class => "google_id"

  #comments
    h3= comment_count
    = render :partial => 'comments/comment', :collection => @post.comments

    = render :partial => 'comments/form'

= render 'layouts/admin_bar'