config/routes.rb
Quill::Application.routes.draw do

  resources :contents

  match '/categories' => 'categories#index'

  match '/archives' => 'archives#index'
  match '/archives/category/:category' => 'archives#category'
  match '/archives/date/:year' => 'archives#date'
  match '/archives/date/:year/:month' => 'archives#date'

  resources :pages do
    collection do
      post 'sort'
    end
  end

  match '/feed' => 'posts#feed', :as => :feed, :defaults => { :format => 'atom' }

  resources :posts do
    resources :comments
  end

  devise_for :authors do
    get 'login' => 'devise/sessions#new'
    post 'login' => 'devise/sessions#create'
    get 'logout' => 'devise/sessions#destroy'
  end

  root :to => 'homepage#index'

end

app/views/layouts/_admin_bar.html.slim
- if author_signed_in?
  div id='admin'
    = link_to "http://en.gravatar.com/", :target => '_blank' do
      img src=current_author.gravatar_url
    ul
      li= link_to current_author.name, root_url
      li= link_to "New Post", "", "data-reveal-id" => "newPost", "data-remote" => "data-remote"
      li= link_to "New Page", "", "data-reveal-id" => "newPage", "data-remote" => "data-remote"
      li= link_to "Reorder Pages", "", "data-reveal-id" => "sortPages", "data-remote" => "data-remote"
      li= link_to "Manage Content", "", "data-reveal-id" => "new_content", "data-remote" => "data-remote"
      - if @page
        li= link_to "Edit Page", "", "data-reveal-id" => "editPage", "data-remote" => "data-remote"
        li= link_to 'Delete Page', @page, "data-remote" => "data-remote", :confirm => 'Are you sure you want to delete this page?', :method => :delete, :remote => true
      - if @post
        li= link_to "Edit Post", "", "data-reveal-id" => "editPost", "data-remote" => "data-remote"
        li= link_to 'Delete Post', @post, "data-remote" => "data-remote", :confirm => 'Are you sure you want to delete this post?', :method => :delete, :remote => true 

      li= link_to "Logout", logout_url

  = render 'posts/new'
  = render 'pages/new'
  = render 'pages/sort'
  = render 'contents/index'
  - if @post
    = render 'posts/edit'
  - if @page
    =render 'pages/edit'

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title
      Quill
      = yield :header
    = stylesheet_link_tag    'application'
    = javascript_include_tag 'application'

    = auto_discovery_link_tag :atom, 'posts/feed'
    = auto_discovery_link_tag :rss, 'posts/feed.rss'
    %link{ :type => 'text/plain', :rel => 'author', :href => '/humans.txt' }

    = csrf_meta_tags

  %body
    #wrapper

      %header
        %h1= link_to "Quill", root_url
        %nav
          %ul
            %li= link_to "Home", root_url
            - header_pages.each do |page|
              %li= link_to page.title, page_url(page)

      %p.notice= notice
      %p.alert= alert

      %section#main(data-pjax-container)
        = yield

      %aside
        = render :partial => 'pages/page', :collection => sidebar_pages

      %footer
        #archives
          %h4 Post Archives
          %dl
            - (start_year..Time.now.strftime("%Y")).reverse_each do |year|
              %dt
                - if Post.where(:created_at => Time.parse("01 #{year}")..(Time.parse("01 #{year}") + 1.year)).exists?
                  = link_to year, archives_path + '/date/' + year
                - else
                  = year
              - (01..12).each do |month|
                %dd
                  - if Post.where(:created_at => Time.parse("#{Date::MONTHNAMES[month]} #{year}")..(Time.parse("#{Date::MONTHNAMES[month]} #{year}") + 1.month)).exists?
                    = link_to Date::ABBR_MONTHNAMES[month], archives_url + '/date/' + year + '/' + Date::MONTHNAMES[month]
                  - else
                    = Date::ABBR_MONTHNAMES[month]

        #twitter
          - cache("tweets", :expires_in => 1.minute) do
            - @twitter = Twitter.user("IanMitchel1")
            %p= raw auto_link(@twitter.status.text)
            #triangle
            = link_to image_tag(@twitter.profile_image_url), 'http://twitter.com/' + @twitter.screen_name
          #copyright
            %span
              &copy; Copyright 2011 Ian Mitchell. Based on
              = link_to 'Quill', 'http://quill.herokuapp.com', { :target => '_blank' }

app/views/layouts/application.html.slim
doctype html
html
  head
    title= site_title
    = stylesheet_link_tag    'application'
    = javascript_include_tag 'application'

    = auto_discovery_link_tag :atom, 'posts/feed'
    = auto_discovery_link_tag :rss, 'posts/feed.rss'

    link type='text/plain' rel='author' href='/humans.txt'

    // Internet Explorer Pinned Site
    meta name="application-name" content="#{site_title}"
    meta name="msapplication-tooltip" content="#{site_title}"
    meta name="msapplication-starturl" content="#{root_url}"
    - sidebar_pages.each do |p|
      meta name="msapplication-task" content="name=#{p.title};action-uri#{page_url(p)}"


    = csrf_meta_tags

  body
    #wrapper
      header
        h1= link_to "Quill", root_url
        nav
          - cache("header", :expires_in => 1.day) do
            ul
              li= link_to "Home", root_url
              - header_pages.each do |page|
                li id="header_page_#{page.id}"= link_to page.title, page_url(page)

      p.notice= notice
      p.alert= alert

      section#main(data-pjax-container)
        = yield

      aside
        - cache("sidebar", :expires_in => 1.day) do
          = render :partial => 'pages/page', :collection => sidebar_pages

      footer
        #archives
          h4 Post Archives
          - cache("archives", :expires_in => 1.day) do
            dl
              - (Post.first.created_at.strftime("%Y")..Time.now.strftime("%Y")).reverse_each do |year|
                dt
                  - posts = Post.where(:created_at => Time.parse("Jan 01 #{year}")..(Time.parse("Jan 01 #{year}") + 1.year))
                  - unless posts.empty?
                    = link_to year, archives_path + '/date/' + year

                    - (01..12).each do |month|
                      - unless posts.empty?
                        - m = posts.first.created_at.strftime("%-m").to_i 
                        - if m == month
                          dd= link_to Date::ABBR_MONTHNAMES[month], archives_url + '/date/' + year + '/' + Date::MONTHNAMES[month]
                          - posts.shift
                        - if m > month
                          dd= Date::ABBR_MONTHNAMES[month]

                        - while m < month
                          - posts.shift
                          - unless posts.empty?
                            - m = posts.first.created_at.strftime("%-m").to_i
                          - else
                            - break
                      - else
                        dd= Date::ABBR_MONTHNAMES[month]

                  - else
                    = year
                    - (01..12).each do |month|
                      dd= Date::ABBR_MONTHNAMES[month]

        #twitter
          - cache("tweets", :expires_in => 1.minute) do
            - if Twitter.rate_limit_status.remaining_hits > 0
              - @twitter = Twitter.user(Author.first.twitter)
              - if @twitter.protected?
                p This account is protected.
                #triangle
                img src="https://si0.twimg.com/sticky/default_profile_images/default_profile_2_normal.png"
              - else
                p= raw auto_link(@twitter.status.text)
                #triangle
                = link_to image_tag(@twitter.profile_image_url), 'http://twitter.com/' + @twitter.screen_name
            - else
              p Rate Limit Exceeded
              #triangle
              = link_to image_tag(Author.first.gravatar_url), 'http://twitter.com/' + Author.first.twitter

          #copyright
            span
              | &copy; Copyright #{Time.new.strftime("%Y")} Ian Mitchell. Based on 
              = link_to 'Quill', 'http://quill.herokuapp.com', { :target => '_blank' }

    javascript:
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', '#{ENV['GOOGLE_ANALYTICS']}']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
       })();